import Image from 'next/image';
import styled from 'styled-components';
import { ReactNode, useEffect } from 'react';


const Content = styled.div`
	display: flex;
	align-items: center;
	justify-content: center;
	flex-wrap: wrap;
	max-width: 800px;
    width: 100%;
`;

const TopSide = styled.div`
	position: sticky;
	top: 0px;
	padding: 20px;
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	background-color: white;
	width: 100%;
	margin: 2rem;
	text-align: center;
	line-height: 1.5;
	font-size: 1.5rem;
	
`;

const Main = styled.div`
	padding: 5rem 0;
	flex: 1;
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
    width: 100%;
`;

const Container = styled.div`
	/* min-height: 100vh; */
	padding: 0 0.5rem;
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
    max-width: 800px;
    width: 100%;
	/* height: 100vh; */
`;

const Footer = styled.footer`
	/* margin-top: 100%; */
	width: 100%;
	height: 60px;
	border-top: 1px solid #eaeaea;
	display: flex;
	justify-content: center;
	align-items: center;
	a {
		display: flex;
		justify-content: center;
		align-items: center;
		flex-grow: 1;
	}
`;

const Wrapper = styled.div`
	display: flex;
	height: 100%;
	width: 100%;
	flex-direction: column;
	align-items: center;
	justify-content: space-between;
	position: absolute;
`;

const HeaderTitle = styled.h1`
	margin: 0;
	line-height: 1.15;
	font-size: 4rem;
	text-align: center;
    width: 100%;
`;

type ConstructPageType = {
	headerTitle?: ReactNode;
	topSide?: ReactNode;
	content?: ReactNode;
};

// styles must mirgate to construct page
const ConstructPage: React.FC<ConstructPageType> = props => {
	return (
		<>
			<header>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</header>
			<Wrapper>
				<Container>
					<Main>
						<HeaderTitle>{props.headerTitle}</HeaderTitle>
						<TopSide>{props.topSide}</TopSide>
						<Content>{props.content}</Content>
					</Main>
				</Container>
				<Footer>
					<div className="flex">
						<a href="https://github.com/RaLLy08" target="_blank" rel="noopener noreferrer">
							Powered by
							<span className="font-semibold pl-1 pr-2">RaLLy08</span>
							<Image src="/git.svg" width={20} height={20} />
						</a>
					</div>
				</Footer>
			</Wrapper>
		</>
	);
};

export default ConstructPage;